# Generate the base64-encoded string for your libvirt password and create the libvirt secret
# echo -n <string> | base64
#
apiVersion: v1
data:
  LibvirtPassword: <base64_password>
  namespace: openstack
kind: Secret
metadata:
  name: libvirt-secret
  namespace: openstack
type: Opaque 
