#Generate a secret of your choice. The secret value in the following code assumes that the secret was generated as:
# echo -n '0P&n$T@<Kr0x' | base64

apiVersion: v1
data:
  AdminPassword: MFAmbiRUQDxLcjB4
  AodhPassword: MFAmbiRUQDxLcjB4
  AodhDatabasePassword: MFAmbiRUQDxLcjB4
  BarbicanDatabasePassword: MFAmbiRUQDxLcjB4
  BarbicanPassword: MFAmbiRUQDxLcjB4
  BarbicanSimpleCryptoKEK: <base64_fernet_key>
  CeilometerPassword: MFAmbiRUQDxLcjB4
  CinderDatabasePassword: MFAmbiRUQDxLcjB4
  CinderPassword: MFAmbiRUQDxLcjB4
  DatabasePassword: MFAmbiRUQDxLcjB4
  DbRootPassword: MFAmbiRUQDxLcjB4
  DesignateDatabasePassword: MFAmbiRUQDxLcjB4
  DesignatePassword: MFAmbiRUQDxLcjB4
  GlanceDatabasePassword: MFAmbiRUQDxLcjB4
  GlancePassword: MFAmbiRUQDxLcjB4
  HeatAuthEncryptionKey: MFAmbiRUQDxLcjB4
  HeatDatabasePassword: MFAmbiRUQDxLcjB4
  HeatPassword: MFAmbiRUQDxLcjB4
  IronicDatabasePassword: MFAmbiRUQDxLcjB4
  IronicInspectorDatabasePassword: MFAmbiRUQDxLcjB4
  IronicInspectorPassword: MFAmbiRUQDxLcjB4
  IronicPassword: MFAmbiRUQDxLcjB4
  KeystoneDatabasePassword: MFAmbiRUQDxLcjB4
  ManilaDatabasePassword: MFAmbiRUQDxLcjB4
  ManilaPassword: MFAmbiRUQDxLcjB4
  MetadataSecret: MFAmbiRUQDxLcjB4
  NeutronDatabasePassword: MFAmbiRUQDxLcjB4
  NeutronPassword: MFAmbiRUQDxLcjB4
  NovaAPIDatabasePassword: MFAmbiRUQDxLcjB4
  NovaAPIMessageBusPassword: MFAmbiRUQDxLcjB4
  NovaCell0DatabasePassword: MFAmbiRUQDxLcjB4
  NovaCell0MessageBusPassword: MFAmbiRUQDxLcjB4
  NovaCell1DatabasePassword: MFAmbiRUQDxLcjB4
  NovaCell1MessageBusPassword: MFAmbiRUQDxLcjB4
  NovaPassword: MFAmbiRUQDxLcjB4
  OctaviaDatabasePassword: MFAmbiRUQDxLcjB4
  OctaviaPassword: MFAmbiRUQDxLcjB4
  PlacementDatabasePassword: MFAmbiRUQDxLcjB4
  PlacementPassword: MFAmbiRUQDxLcjB4
  SwiftPassword: MFAmbiRUQDxLcjB4
kind: Secret
metadata:
  name: osp-secret
  namespace: openstack
type: Opaque
